# docker-compose.yml
version: '3.5'
services:
  pocserviceapi:
    container_name: pocserviceapi 
    image: poc.serviceapi
    build:
      context: .
      dockerfile: POC.ServiceAPI/Dockerfile
      args:
        - SERVICE_PORT=80
    ports:
        - "8881:80"

  pocserviceworker:
    container_name: pocserviceworker
    image: poc.serviceworker
    build:
      context: .
      dockerfile: POC.ServiceWorker/Dockerfile
      args:
        - SERVICE_PORT=80
    ports:
        - "8882:80"
